### ISSUE TITLE
팀 프로비저닝 세팅하기

### ISSUE THREAD

**Issue by song-cool** [DeveloperAcademy-POSTECH/Hangleton_Team8_LightHouse#11]
리버가 잘알려주셔서 그대로 진행을 하겠습니다!
이번 PR이 머지되는대로 작업 진행할께요!

**Comment by RuyHa** [comment]
해당 이슈는 해결 되었음으로 클로즈 하겠습니다.
같이 자료를 찾고 고생해주신 리버, 송쿨 고생하셨습니다.
