### ISSUE TITLE
동작 없음 및 이미지 설명 없는 페이지 이미지 추가

### ISSUE THREAD

**Issue by RuyHa** [DeveloperAcademy-POSTECH/Hangleton_Team8_LightHouse#3]
동작은 하지 않더라고 어떻게 동작 시켜야 하는지 이미지는 추가 하는게 좋을 것 같습니다.

**Comment by GroundDev** [comment]
영어로는 Do nothing으로 표현하는 듯 합니다.
관련하여 이미지를 찾아보면 좋은 힌트를 얻을 수 있을 것 같습니다.

**Comment by RuyHa** [comment]
해당 이슈는 해결 되었음으로 클로즈 하겠습니다.
