### ISSUE TITLE
로컬라이징 처리하기

### ISSUE THREAD

**Issue by RuyHa** [DeveloperAcademy-POSTECH/Hangleton_Team8_LightHouse#5]
리젝 사유중 하나는 테스터가 한글을 읽지 못해 생긴 이슈 같습니다.
로컬라이징 처리를 하면 좋을 것 같은데
전에 말씀해 주신대로 넘버스나 엑셀을 활용해서 작업하면 좋을 것 같습니다.
안된다면 수작업으로 해도 문제는 안될 것 같습니다.

**Comment by RuyHa** [comment]
Localizing 으로 브랜치 따서 작업하겠습니다.

**Comment by GroundDev** [comment]
기존 넘버스에 있는 Subtitle과 content를 영어로 번역해서 올리겠습니다.
로컬라이징 처리를 해 주는 처리기를 다 만들어두셨는데 제가 번역해서 올리는 작업이 늦어서 전체적인 작업에 지연이 발생해서 미안합니다.
오늘 저녁 10시 경 부터 작업하여 최소한 밤 12시 전까지는 전부 번역하도록 하겠습니다.
![image](https://user-images.githubusercontent.com/103012763/195546156-9a07f70e-a45a-45a0-8a88-24055411d730.png)

**Comment by GroundDev** [comment]
번역 완료했습니다! 넘버스 파일에 업데이트 했습니다.
혹시 보시고 번역이 이상한 부분이 있다거나 더 좋은 표현이 있다면 적극적으로 수정해주세요(저도 파파고 형님 많이 애용했습니다).

**Comment by RuyHa** [comment]
작업 완료했습니다.!! 해당 이슈 클로즈 하겠습니다.
